import Foundation

/// The exact shape of the two config edits. Pure string and dictionary work, kept apart from
/// the file handling so the formats can be tested without writing to anyone's home directory.
enum ClaudeRouting {
    /// A base URL claudex is willing to replace. Anything else in this key belongs to the user
    /// or their organisation, and the installer refuses rather than repointing it.
    static func isClaudexURL(_ value: String) -> Bool {
        guard let url = URL(string: value) else { return false }
        return (url.host == "127.0.0.1" || url.host == "localhost") && url.path.hasPrefix("/\(ProviderKind.claude.rawValue)")
    }

    /// `ANTHROPIC_CUSTOM_HEADERS` is one `Name: Value` per line, newline separated inside the
    /// JSON string. Claudex owns exactly one of those lines.
    static func headers(replacingTokenIn existing: String?, with token: String) -> String {
        var lines = otherLines(existing)
        lines.append("\(ProxyEndpoint.tokenHeader): \(token)")
        return lines.joined(separator: "\n")
    }

    /// Returns nil when nothing of the user's is left, so uninstall can drop the key instead of
    /// leaving an empty string behind.
    static func headers(removingTokenFrom existing: String?) -> String? {
        let lines = otherLines(existing)
        return lines.isEmpty ? nil : lines.joined(separator: "\n")
    }

    static func token(in existing: String?) -> String? {
        for line in (existing ?? "").split(separator: "\n") {
            let parts = line.split(separator: ":", maxSplits: 1)
            guard parts.count == 2,
                  parts[0].trimmingCharacters(in: .whitespaces).caseInsensitiveCompare(ProxyEndpoint.tokenHeader) == .orderedSame
            else { continue }
            return parts[1].trimmingCharacters(in: .whitespaces)
        }
        return nil
    }

    private static func otherLines(_ existing: String?) -> [String] {
        (existing ?? "")
            .split(separator: "\n")
            .map(String.init)
            .filter { line in
                let name = line.split(separator: ":", maxSplits: 1).first?.trimmingCharacters(in: .whitespaces) ?? ""
                return name.caseInsensitiveCompare(ProxyEndpoint.tokenHeader) != .orderedSame
            }
    }
}

enum CodexRouting {
    static let providerKey = "claudex"

    /// `requires_openai_auth` stays true so Codex keeps attaching its own bearer. The proxy
    /// drops that header before going upstream and authenticates on `X-Claudex-Token`; leaving
    /// the flag off would change how Codex builds the request, not just what it sends.
    ///
    /// `wire_api = "responses"` because it is the only wire format current Codex accepts.
    static func block(_ endpoint: ProxyEndpoint) -> String {
        """

        \(TOMLEdit.blockStart)
        # Generated by Claudex. Edits here are lost on the next install, and stop uninstall
        # from cleaning up. Turn routing off in Claudex > Settings instead.
        [model_providers.\(providerKey)]
        name = "Claudex"
        base_url = "\(endpoint.baseURL(for: .codex).absoluteString)"
        wire_api = "responses"
        requires_openai_auth = true

        [model_providers.\(providerKey).http_headers]
        "\(ProxyEndpoint.tokenHeader)" = "\(endpoint.token)"
        \(TOMLEdit.blockEnd)

        """
    }
}

/// The smallest TOML editing that does the job: find a top-level key, and replace a fenced
/// block. Not a parser.
///
/// A real round-trip TOML editor is a dependency claudex does not need, but the two operations
/// here still have to be exact, because the file they touch is one the user also edits. Both
/// are line-oriented and neither reformats anything it did not write.
enum TOMLEdit {
    static let blockStart = "# >>> claudex managed block"
    static let blockEnd = "# <<< claudex managed block"

    /// The managed block's body, or nil when it is absent.
    static func managedBlock(in toml: String) -> String? {
        let lines = toml.components(separatedBy: "\n")
        guard let start = lines.firstIndex(where: { $0.hasPrefix(blockStart) }),
              let end = lines.firstIndex(where: { $0.hasPrefix(blockEnd) }),
              start < end
        else { return nil }
        return lines[(start + 1)..<end].joined(separator: "\n")
    }

    static func removingManagedBlock(from toml: String) -> String {
        let lines = toml.components(separatedBy: "\n")
        guard let start = lines.firstIndex(where: { $0.hasPrefix(blockStart) }),
              let end = lines.firstIndex(where: { $0.hasPrefix(blockEnd) }),
              start < end
        else { return toml }
        var remaining = Array(lines[..<start]) + Array(lines[(end + 1)...])
        while remaining.last?.isEmpty == true { remaining.removeLast() }
        return remaining.joined(separator: "\n") + "\n"
    }

    /// A bare `key = value` line, which in TOML means the key belongs to whichever table
    /// header precedes it. Only the run of lines before the first header is top level, so that
    /// is the only place this looks — and the only place it will write.
    static func topLevelValue(_ key: String, in toml: String) -> String? {
        let lines = toml.components(separatedBy: "\n")
        for line in lines[..<firstTableIndex(lines)] {
            guard let value = assignment(key, on: line) else { continue }
            return value
        }
        return nil
    }

    /// Sets, replaces or (with nil) removes a top-level key, leaving every other line as it was.
    static func settingTopLevel(_ key: String, to value: String?, in toml: String) -> String {
        var lines = toml.components(separatedBy: "\n")
        let boundary = firstTableIndex(lines)
        let existing = lines[..<boundary].firstIndex { assignment(key, on: $0) != nil }

        switch (existing, value) {
        case (let index?, let value?):
            lines[index] = "\(key) = \"\(escape(value))\""
        case (let index?, nil):
            lines.remove(at: index)
        case (nil, let value?):
            // Ahead of the first table header, because after one the key would silently become
            // a member of that table instead of a top-level setting.
            lines.insert("\(key) = \"\(escape(value))\"", at: boundary)
        case (nil, nil):
            break
        }
        return lines.joined(separator: "\n")
    }

    /// The value of `key = "..."` anywhere in a fragment. Used on the managed block, whose
    /// contents claudex wrote and whose shape it therefore knows.
    static func value(of key: String, in fragment: String) -> String? {
        for line in fragment.components(separatedBy: "\n") {
            if let value = assignment(key, on: line) { return value }
        }
        return nil
    }

    private static func firstTableIndex(_ lines: [String]) -> Int {
        lines.firstIndex { $0.trimmingCharacters(in: .whitespaces).hasPrefix("[") } ?? lines.count
    }

    private static func assignment(_ key: String, on line: String) -> String? {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard !trimmed.hasPrefix("#") else { return nil }
        let parts = trimmed.split(separator: "=", maxSplits: 1)
        guard parts.count == 2, parts[0].trimmingCharacters(in: .whitespaces) == key else { return nil }
        var value = parts[1].trimmingCharacters(in: .whitespaces)
        if let comment = value.range(of: " #"), !value.hasPrefix("\"") {
            value = String(value[..<comment.lowerBound]).trimmingCharacters(in: .whitespaces)
        }
        guard value.hasPrefix("\""), value.hasSuffix("\""), value.count >= 2 else { return value }
        return unescape(String(value.dropFirst().dropLast()))
    }

    private static func escape(_ value: String) -> String {
        value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
    }

    private static func unescape(_ value: String) -> String {
        value.replacingOccurrences(of: "\\\"", with: "\"").replacingOccurrences(of: "\\\\", with: "\\")
    }
}
